[package]
name = "rust-design-patterns"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "perf_bench"
harness = false

[dependencies]
